# Generated by Django 2.2.5 on 2019-10-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omni', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
