# Generated by Django 2.2.5 on 2019-09-21 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omni', '0002_auto_20190920_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='omni.Event'),
        ),
    ]
