# Generated by Django 2.2.5 on 2019-09-21 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omni', '0003_auto_20190920_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='teams',
            field=models.ManyToManyField(related_name='event_team', to='omni.Team'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='omni.Team'),
        ),
    ]
