# Generated by Django 2.2.5 on 2019-09-23 15:00

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('omni', '0004_auto_20190920_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='omni.Event'),
        ),
        migrations.RemoveField(
            model_name='outcome',
            name='winner',
        ),
        migrations.AddField(
            model_name='outcome',
            name='winner',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='event', chained_model_field='teams', horizontal=True, to='omni.Team'),
        ),
    ]
