# Generated by Django 2.2.5 on 2019-09-24 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omni', '0007_auto_20190924_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='omni.Event'),
        ),
    ]
