# Generated by Django 2.2.5 on 2019-09-18 20:00

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', users.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='grade',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
    ]
